### ISSUE TITLE
tracking missing build UI

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#11]
The build UI should follow `docker build` and be compatible with for a possibility to merge the tools in the future.

Tracking things currently missing (add things):

- [x] remote contexts (git, https)
- [ ] `-f` symlink
- [x] `-f -`
- [x] tar context form stdin
- [x] `--cache-from` + updates to other importers
- [x] extra hosts (+ net via entitlements?)
- [x] `-q`
- [x] `--iidfile`
- [ ] `--squash` ?
- [x] `-o type=docker` to load into docker (+ a driver specific default would be nice)
- [x] new: `--cache-to`
- [ ] `--security-opt`
- [ ] `--force-rm`
- [ ] `--network=custom`
- [ ] `--compress`

@tiborvass

**Comment by grzegorzskowronski** [comment]
hi, are there any estimations when --squash could be implemented? I think it would be also helpful if buildx build documentation would state which options are not yet available/implemented like --squash: https://docs.docker.com/engine/reference/commandline/buildx_build/
